### ISSUE TITLE
t.setConfig is not a function

### ISSUE THREAD

**Issue by mattbruman** [bramkragten/swipe-card#26]
On version 4.0 and am getting this all the time, only way to clear it is to open lovelace editor move the tab its on left or right then move it back.

**Comment by Sha-Darim** [comment]
I have the same issue. Reloading the page numerous times seems to "fix" the problem, but it still comes back...

**Comment by haywiremk** [comment]
Same issue cannot even get this card to work using Home Assistant 2021.5.5
chunk.e176e418edcf4883a584.js:2544 card custom:swipe-card TypeError: t.setConfig is not a function
    at HTMLElement._createCardElement (swipe-card.js:38)
    at swipe-card.js:19
    at Array.map (<anonymous>)
    at HTMLElement.setConfig (swipe-card.js:19)

**Comment by anndrewww** [comment]
FWIW I have this issue, but only when I set my "Mobile" Lovelace Dashboard containing the offending swipe-card to be the default on my mobile device.

**Comment by ronschaeffer** [comment]
Any update on this? Great card, but this is happening often and seemingly randomly. Thanks.

**Comment by caohuongls** [comment]
I have same trouble when I created 2 swipe card on same view. When I removed one of them. It's worked

**Comment by GreeMart** [comment]
Error still present from iOS companion app and pc browsers (firefox/chrome). adding a new card and delete it right after seems is a workaround but doesn't solve it permanently.

**Comment by Marcus1410** [comment]
Error still present as of 16/09/24, please fix this :)
